/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Model.Conta;
import Model.Despesa;
import Model.Lancamento;
import Model.Receita;

/**
 * Classe responsável pela geração e exibição de um relatório contendo os lançamentos
 * financeiros de uma conta. Permite visualizar o histórico de receitas e despesas,
 * com informações detalhadas de cada lançamento e o saldo atualizado.
 * 
 * Funcionalidades principais:
 * - Exibe os lançamentos financeiros ordenados por data.
 * - Calcula e exibe o saldo após cada movimento.
 * - Apresenta informações do titular da conta, caso disponível.
 * 
 */
public class FExtrato extends javax.swing.JDialog {

    /**
     * Creates new form FRelatorio
     */
    public FExtrato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    /**
     * Gera o relatório de lançamentos da conta e exibe no campo de texto.
     * O relatório exibe informações detalhadas de cada lançamento, incluindo:
     * Tipo do lançamento (Receita ou Despesa)
     * Valor
     * Categoria
     * Data do lançamento
     * Saldo atualizado após cada movimento
     *
     * @param conta A conta cujos lançamentos serão exibidos no relatório.
     */
    public void exportarRelatorio(Conta conta) {
        if (conta.getLancamentos().size() == 0) {
            taRelatorio.append("A conta não possui lançamentos.");
        } else {
            if (conta.getTitular() == null || conta.getTitular().getNome().isEmpty()) {
                taRelatorio.append("Nao foi definido nenhum titular para esta conta. \n");
                taRelatorio.append("\n");
            } else {
                taRelatorio.append("Titular: " + conta.getTitular().getNome() + "\n");
                taRelatorio.append("\n");
            }
            double saldoNoMomento = 0;
            for (Lancamento lancamento : conta.listarLancamentosOrdenadosData(conta.getLancamentos())) {
                if (lancamento instanceof Despesa) {
                    Despesa despesa = (Despesa) lancamento;
                    taRelatorio.append("DESPESA - Valor: " + despesa.getValor() + " | Categoria: " + despesa.getCategoria() + " | Data Lancada: " + despesa.getData() + "\n");
                    saldoNoMomento -= despesa.getValor();
                    taRelatorio.append("Saldo Atual: " + String.format("R$ %.2f", saldoNoMomento) + "\n\n");
                } else if (lancamento instanceof Receita) {
                    Receita receita = (Receita) lancamento;
                    taRelatorio.append("RECEITA - Valor: " + receita.getValor() + " | Categoria: " + receita.getCategoria() + " | Data Lancada: " + receita.getData() + "\n");
                    saldoNoMomento += receita.getValor();
                    taRelatorio.append("Saldo Após o movimento: " + String.format("R$ %.2f", saldoNoMomento) + "\n\n");
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taRelatorio = new javax.swing.JTextArea();
        btFechar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        taRelatorio.setEditable(false);
        taRelatorio.setBackground(new java.awt.Color(84, 84, 84));
        taRelatorio.setColumns(20);
        taRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        taRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        taRelatorio.setRows(5);
        jScrollPane2.setViewportView(taRelatorio);

        btFechar.setBackground(new java.awt.Color(102, 102, 102));
        btFechar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btFechar.setForeground(new java.awt.Color(255, 255, 255));
        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Extrato de Lançamentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btFechar)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(168, 168, 168))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btFechar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Ação acionada ao clicar no botão "Fechar". Fecha o diálogo de forma segura.
     *
     */
    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FExtrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FExtrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FExtrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FExtrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechar;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taRelatorio;
    // End of variables declaration//GEN-END:variables
}
